### PR TITLE
Swift 4.2

### PR DESCRIPTION
**Pull request by raysarebest**
This fixes issue #19 I ran the Swift conversion tool, pointed Xcode to a couple misplaced localization files, and fixed a couple linter warnings

### CODE REVIEW

**Comment by raysarebest** [comment]
CI still fails on this currently because the [BarcodeScanner](https://github.com/hyperoslo/BarcodeScanner) pod hasn't been updated to Swift 4.2 yet, though the conversion tool works for it in nearly all cases

**Comment by bcye** [comment]
So we would need to fork it, update it ourselves, and include our fork in the Podfile, instead of the original Pod?

**Comment by raysarebest** [comment]
Yes, though there appear to be some forks already on that repo with similar goals, though I think they're mostly outdated relative to that project's master

**Comment by bcye** [comment]
Can you link the forks?

**Comment by bcye** [comment]
#23

**Comment by raysarebest** [comment]
- There's one here that's outdated against the project's `master` branch: https://github.com/hyperoslo/BarcodeScanner/pull/114
- There's another one here whose build fails according to that project's CI: https://github.com/hyperoslo/BarcodeScanner/pull/134

**Comment by raysarebest** [comment]
I'm pretty sure CoreImage has a scanner built in. Why not just use it directly? Better yet, it looks like there's a [Vision framework](https://developer.apple.com/documentation/vision) in iOS 11+

**Comment by bcye** [comment]
Didn‘t know that. Do you think you could implement it?

**Comment by raysarebest** [comment]
Most likely, given a few hours to a weekend of work. I'd basically have to make the barcode view controller myself. Is that something you'd like me to try?

**Comment by bcye** [comment]
Sure, if you can handle it, I’m busy preparing the iMessage app

**Comment by bcye** [comment]
Could you remove the Pods directory from the gitignore and remove the note in the readme that one needs to do Pods install

**Comment by bcye** [comment]
This should resolve CI and other issues

**Comment by bcye** [comment]
because if it fails on CI it'll fail on every other machine then yours

**Comment by bcye** [comment]
(for example mine)

**Comment by bcye** [comment]
let's see if it passes...

**Review by bcye — CHANGES_REQUESTED** [review]
please also remove the notice in the repos readme

**Review by bcye — APPROVED** [review]

**Comment by raysarebest** [comment]
I did that right as you were commenting. Are there any CI config files that need to be modified so it knows not to run `pod install`?

**Comment by bcye** [comment]
yes it says before script pod install, just remove that section

**Pull request merged**
