### PR TITLE
Migrate from GoogleBooks to OpenLibrary

### PR DESCRIPTION
**Pull request by damien-rivet**
Implements #13.

Added SwiftLint (applied fixes).
Removed missing `keys.plist` from build.
Added `OpenLibraryService` basic implementation.
Added `OpenLibraryBook` (along with UT).
Removed `ISBNSearcher`.
Performed additional clean up.
Added TravisCI.

### CODE REVIEW

**Comment by damien-rivet** [comment]
**TravisCI** is now in place by this PR, you should be able to link your account with **TravisCI** to take over my instance.

**Comment by bcye** [comment]
Woooooow! Thanks so much, this is just awesome!
I've kinda a full day today so I will probably review the PR tomorrow.

**Comment by bcye** [comment]
Could you recommend good ressources to learn more about swift lint?

**Comment by damien-rivet** [comment]
@bcye well, there's no resources *per se* for **SwiftLint**.

It's just a script that run over your code and check for *code smells* (aka things that make the code harder to maintain).

I can only recommend you to check the official repository at: https://github.com/realm/SwiftLinthttps://github.com/realm/SwiftLint

**SwiftLint** is just here to help enforce good coding practices (e.g. tabs instead of spaces, no whitelines, etc.) which in turns, ease the long-term maintenance and reduce the codebase.

**Comment by bcye** [comment]
Hey, @Ethenyl would you be interested in becoming a collaborator in this project.

**Comment by damien-rivet** [comment]
Hi @bcye,

I'm more than happy to help on the project but I'm not sure I'll make a great collaborator since I'm not that present on GitHub (like most of us...).

But if you feel like adding me, why not, I'll try to help whenever an issue pops up.

**Comment by bcye** [comment]
I've added you. It would be great if you'd join the slack workspace (click on slack in the readme)

**Pull request merged**
