### PR TITLE
Add Russian translate

### PR DESCRIPTION
**Pull request by pankova**
Issue #7: add Russian translate

### CODE REVIEW

**Comment by bcye** [comment]
@pankova Your localization seems to have issues. The text field shows up 2 times. Could you fix this?

**Comment by pankova** [comment]
Tomorrow I’ll try fix it :)

**Comment by bcye** [comment]
@pankova Perfect thanks! Maybe its because it's double translated or so

**Comment by pankova** [comment]
@bcye did you talk about
`/* Class = "UITextField"; placeholder = "What's the title of the book?"; ObjectID = "3ho-zi-bO4"; */` ? 
In German localization i also see it twice. Are you sure, the problem isn't in original strings?

**Comment by bcye** [comment]
Hmm? I didn't see it twice when I merged the German one. I'm gonna reclone your fork and look if it wasn't some error of xcode being xcode

**Pull request merged**
