### PR TITLE
Cleaner API model

### PR DESCRIPTION
**Pull request by raysarebest**
This PR addresses Issue #27 by marking all properties of `OpenLibraryBook` and `OpenLibraryBookDetails` as optional, except the `title`. There are also some miscellaneous small things I fixed/refactored a bit in my testing as I noticed them

### CODE REVIEW

**Review by bcye — CHANGES_REQUESTED** [review]
Why did you delete showsummary.storyboard

**Comment by raysarebest** [comment]
I didn't, that was Xcode. That particular file seems to be some kind of Xcode-internal cache or something like that. Similar files show in my filesystem, but not in Xcode. Xcode must've deemed it unnecessary, and deleted it as a result. Everything still works/runs fine with this PR

**Review by bcye — APPROVED** [review]

**Comment by bcye** [comment]
ok just checking

**Comment by bcye** [comment]
we need your review then

**Comment by raysarebest** [comment]
I can't review my own PR. Another owner/collaborator will have to review it

**Comment by bcye** [comment]
lulz, gonna force merge it then

**Pull request merged**
