### PR TITLE
Swedish localization

### PR DESCRIPTION
**Pull request by raysarebest**
This adds a fix for Issue #7 for the Swedish language

### CODE REVIEW

**Comment by bcye** [comment]
CI failing, have you started working on 4.2 upgrade accidentally on master?

**Comment by raysarebest** [comment]
I did my work for this PR on the `swedish` branch on my fork, which branches from `swift-4.2`, which is the branch I made my Swift 4.2 PR with. `swift-4.2` branches from this project's `master`. I did it like that because I had compiler errors otherwise. Is there a different branch I should've started on?

To be clear, both of my recent PRs compile and run just fine in Xcode 10/iOS 12 on my Mac, no matter what the CI says

**Comment by bcye** [comment]
Yes, because this way it won't compile (CI). What were the compiler errors on master branch?

**Comment by raysarebest** [comment]
A couple files for the French localization were misplaced, and they were causing Xcode's build to fail. I fixed that in my Swift 4.2 PR

**Comment by bcye** [comment]
could you branch another Swedish branch from master, and import the localizations over?

**Comment by raysarebest** [comment]
I think these CI builds are going to fail regardless until we use pods that are updated for Swift 4.2, however. 2 pods used by `master` haven't been updated on cocoapods.org yet. I pointed the placeholder text view one to point to that project's GitHub `master`, but there's been no such update for the barcode scanner yet

**Comment by raysarebest** [comment]
Sure, will do. Do you want me to fix the misplaced files issue in that one, too?

**Comment by bcye** [comment]
They were perfectly fine in the last PRs. They were set up in #15

**Comment by raysarebest** [comment]
I just did a fresh download from `master` and `pod install`ed and the build error is still there

**Comment by bcye** [comment]
ok, I'm gonna look at this later then, and merge it

**Comment by raysarebest** [comment]
Awesome. Do you still want me to redo my localization from `master` and open a new PR? What about the new barcode scanning implementation?

**Comment by bcye** [comment]
Could you please do everything in a different branch, which all are branched from master, that way there will be less merging issues and complications.

**Comment by raysarebest** [comment]
Sure, will do, though I'll wait until the build error/Swift 4.2 stuff is merged into `master` so Xcode doesn't have to be warning me about stuff all the time :P

**Comment by bcye** [comment]
You mean the PR #20

**Comment by bcye** [comment]
into bcye:master

**Comment by raysarebest** [comment]
Exactly. That's just a simple fix for the build error and conversion to the latest Swift for this project

**Comment by bcye** [comment]
I thought it had issues with the outdated library

**Comment by raysarebest** [comment]
I fixed all that could be fixed. There's only 1 library that doesn't have a Swift 4.2 update available, which is the barcode scanner one. As far as actual compilation goes, #20 works on my machine because I did the simple conversions myself in that library's source code in the `Pods` project (which isn't committed), but the CI will always fail until we change that library out because it downloads the outdated pod every time

**Comment by raysarebest** [comment]
I'd like to base new work of updating that library off of a version that has all the other issues fixed, unless you want me to work directly in #20's branch

**Pull request merged**
