### PR TITLE
Added share book functionality

### PR DESCRIPTION
**Pull request by shashikanth-a**

### CODE REVIEW

**Comment by bcye** [comment]
Hey, I‘m gonna take a look at it when I come home and merge it then. Why did you change the Podfile.lock

**Comment by shashikanth-a** [comment]
Different version of CocoaPods on my system. Should not be a problem.

**Comment by bcye** [comment]
@shashikanth-a Huge thanks for your contribution. 👍 👏
I just changed some UI things, do you still want to work on the other issue?

**Comment by shashikanth-a** [comment]
Yes ... I’m working on it.

**Comment by bcye** [comment]
Awesome! Thanks again.
On Oct 10, 2018, 10:32 PM -0700, shashikanth-a <notifications@github.com>, wrote:
Yes ... I’m working on it.

**Pull request merged**
