### PR TITLE
Add German localization

### PR DESCRIPTION
**Pull request by ffittschen**
According to #7 I translated the app to German.

In addition to the Storyboards and the Info.plist, I also tracked down strings throughout the code and extracted them into a `Localizable.strings` file to localize them as well.

Since the `summarizeTextView` uses a custom UITextView subclass, it was not automatically added to the `Main.strings` file by Xcode and manually adding the key (`4cd-EC-sfb.placeholder`) to the generated file did not work. Therefore, I added the localized string in code in `AddViewController.swift`.

### CODE REVIEW

**Comment by bcye** [comment]
Awesome, thanks for going the extra mile! Actually, I started localizing it to German too, but Xcode crashed all the time when importing. Whatever, I'm gonna look over it, resolve merge issues and hopefully merge it.

**Comment by ffittschen** [comment]
I actually didn't do the export/import dance with those localization files. I directly localized within Xcode. This worked stable though! The only catch was pressing the "Localize..." button in the Inspector Pane of the `Info.plist`. This didn't work out, because it duplicated the resource, which cannot work with specifying a single `Info.plist` in the build settings 🤷🏼‍♂️ I guess I'll have to file a radar

**Comment by pankova** [comment]
>I started localizing it to German too, but Xcode crashed all the time when importing.

I also had stable Xcode crash on import localization %) The answer from stackoverflow https://stackoverflow.com/questions/41339751/xcode-8-localization-import-crash helps me 

`xcodebuild -verbose -importLocalizations -localizationPath "lang.xliff" -project ./myProject.xcodeproj
`

Console is the most reliable way :D

**Comment by bcye** [comment]
Oh thx.
Tho, I was working with the new .xcloc file format
On Oct 18, 2018, 8:01 AM -0700, pankova <notifications@github.com>, wrote:

I started localizing it to German too, but Xcode crashed all the time when importing.

**Comment by pankova** [comment]
>Tho, I was working with the new .xcloc file format

I thought also in this case you need import only .xliff

**Comment by bcye** [comment]
Hey, @ffittschen would you be interested in becoming a collaborator of this project?

**Pull request merged**
